name: "Check diagrams"
description:
  "Checks that PlantUML diagrams are correctly generated for every commit."
author: "Ventus218"
inputs:
  gen_diagrams_command:
    description:
      "Command to run in order to generate diagrams. For example:
      ./gen_puml_diagrams.sh"
    required: true
  fail_fast:
    description:
      "If true, stop on first failing commit. If false, run all commits and
      report failure at the end."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Check every commit
      shell: bash
      run: |
        set -eu

        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
          echo "Pull request detected"
        elif [ "${{ github.event_name }}" = "push" ]; then
          BASE_COMMIT="${{ github.event.before }}"
        else 
          echo "Triggered by unexpected event ${{ github.event_name }}"
          echo "Only pull_request and push are supported"
          exit 1
        fi
        HEAD="${{ github.sha }}"
        if [ "${{ inputs.fail_fast }}" = "true" ]; then
          FAIL_FAST="-f"
        fi

        # ${FAIL_FAST:+$FAIL_FAST} means "if FAIL_FAST is null or not set do nothing, otherwise insert $FAIL_FAST"
        # which is what we want in order not to pass an empty string "". We cannot quote it, though it doesn't
        # contain injected input
        "${{ github.action_path }}"/action.sh ${FAIL_FAST:+$FAIL_FAST} "$BASE_COMMIT" "$HEAD" "${{ inputs.gen_diagrams_command }}"
